<a href="https://colab.research.google.com/github/serivan/DeepLearning/blob/master/numerical_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rounding and truncation errors

Adding a very small numb er to a larger one may have no effect. This can cause large changes downstream:

In [2]:
import numpy as np
import tensorflow as tf

sess = tf.InteractiveSession()

/home/iserina/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/iserina/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/iserina/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/iserina/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:5

In [3]:
a = np.array([0., 1e-8]).astype('float32')
a

array([0.e+00, 1.e-08], dtype=float32)

In [4]:
(a+1)

array([1., 1.], dtype=float32)

In [5]:
a+1

array([1., 1.], dtype=float32)

exp(x) overflows for large x

In [8]:
x=88
np.exp(x).astype('float32')

1.6516363e+38

In [12]:
x=-103
np.exp(x).astype('float32')

1e-45

log(0) = - inf

In [15]:
np.log(1)

0.0

#log(sum(exp))
Naive implementation
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf

In [30]:
a = np.array([ -100]).astype('float32')
np.log(np.sum(np.exp(a)))

-99.98309

In [38]:
a = np.array([0,88]).astype('float32')
np.log(np.sum(np.exp(a)))

/home/iserina/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


inf

Stable version

In [39]:
mx=np.max(a)
safe_array=a-mx
log_sum_exp= mx + np.log(np.sum(np.exp(safe_array)))
log_sum_exp                          

89.0

Built in versions

In [44]:
np.logaddexp.reduce(a)

89.0

In [45]:
from scipy.special import logsumexp
logsumexp(a)

89.0

In [49]:
#Tensorflow
sess = tf.Session()
print(sess.run( tf.reduce_logsumexp(a) ))

89.0


In [70]:
logits=np.array([-1010,189]).astype('float32')
safe_logits = logits - tf.reduce_max(logits)
#softmax = tf.nn.softmax(safe_logits)
softmax = tf.nn.softmax(logits)
print(sess.run( softmax ))

[0. 1.]
