<a href="https://colab.research.google.com/github/serivan/DeepLearning/blob/master/02-Preliminaries/numerical_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
# Rounding and truncation errors

Adding a very small numb er to a larger one may have no effect. This can cause large changes downstream:

In [49]:
import numpy as np
import tensorflow as tf

sess = tf.compat.v1.InteractiveSession()

In [50]:
a = np.array([0., 1e-8]).astype('float32')
a

array([0.e+00, 1.e-08], dtype=float32)

In [51]:
(a+1)

array([1., 1.], dtype=float32)

In [52]:
a+1

array([1., 1.], dtype=float32)

exp(x) overflows for large x

In [53]:
x=88
np.exp(x).astype('float32')

1.6516363e+38

In [54]:
x=-103
np.exp(x).astype('float32')

1e-45

log(0) = - inf

In [55]:
np.log(1)

0.0

#log(sum(exp))
Naive implementation
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf

In [56]:
a = np.array([ -100]).astype('float32')
np.log(np.sum(np.exp(a)))

-99.98309

In [57]:
a = np.array([0,88]).astype('float32')
np.log(np.sum(np.exp(a)))

88.0

Stable version

In [58]:
mx=np.max(a)
safe_array=a-mx
log_sum_exp= mx + np.log(np.sum(np.exp(safe_array)))
log_sum_exp                          

88.0

Built in versions

In [59]:
np.logaddexp.reduce(a)

88.0

In [60]:
from scipy.special import logsumexp
logsumexp(a)

88.0

In [61]:
#Tensorflow
sess = tf.compat.v1.Session()
print(sess.run( tf.reduce_logsumexp(a) ))

RuntimeError: ignored

In [ ]:
logits=np.array([-1010,189]).astype('float32')
safe_logits = logits - tf.reduce_max(logits)
#softmax = tf.nn.softmax(safe_logits)
softmax = tf.nn.softmax(logits)
print(sess.run( softmax ))