<a href="https://colab.research.google.com/github/serivan/DeepLearning/blob/master/02-Preliminaries/numerical_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rounding and truncation errors

Adding a very small numb er to a larger one may have no effect. This can cause large changes downstream:

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = np.array([0., 1e-8]).astype('float32')
a

array([0.e+00, 1.e-08], dtype=float32)

In [3]:
a+1

array([1., 1.], dtype=float32)

##exp(x) overflows for large x

In [4]:
x=88
np.exp(x).astype('float32')

1.6516363e+38

In [5]:
x=-100 #Check what happen at different values of x
np.exp(x).astype('float32')

3.8e-44

log(0) = - inf

In [6]:
np.log(0)

<ipython-input-6-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

#log(sum(exp))
Naive implementation
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf

In [8]:
a = np.array([0,88]).astype('float32')
np.log(np.sum(np.exp(a)))

88.0

In [9]:
a = np.array([ -100]).astype('float32')
np.exp(a)

array([3.8e-44], dtype=float32)

In [10]:
np.log(np.sum(np.exp(a)))

-99.98309

Stable version

In [11]:
a = np.array([0,100]).astype('float32')
mx=np.max(a)
safe_array=a-mx
log_sum_exp= mx + np.log(np.sum(np.exp(safe_array)))
log_sum_exp

100.0

Built in versions

In [12]:
np.logaddexp.reduce(a)

100.0

In [13]:
from scipy.special import logsumexp
logsumexp(a)

100.0

In [14]:
tf.reduce_logsumexp(a)

<tf.Tensor: shape=(), dtype=float32, numpy=100.0>