<a href="https://colab.research.google.com/github/serivan/DeepLearning/blob/master/02-Preliminaries/numerical_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rounding and truncation errors

Adding a very small numb er to a larger one may have no effect. This can cause large changes downstream:

In [1]:
import numpy as np

In [2]:
a = np.array([0., 1e-8]).astype('float32')
a

array([0.e+00, 1.e-08], dtype=float32)

In [3]:
(a+1)

array([1., 1.], dtype=float32)

In [4]:
a+1

array([1., 1.], dtype=float32)

exp(x) overflows for large x

In [8]:
x=88
np.exp(x).astype('float32')

1.6516363e+38

In [10]:
x=-103
np.exp(x).astype('float32')

0.0

log(0) = - inf

In [11]:
np.log(0)

/home/iserina/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

#log(sum(exp))
Naive implementation
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf

In [13]:
a = np.array([ -100]).astype('float32')
np.log(np.sum(np.exp(a)))

-99.98309

In [21]:
a = np.array([0,88]).astype('float32')
np.log(np.sum(np.exp(a)))

88.0

Stable version

In [23]:
a = np.array([0,88]).astype('float32')
mx=np.max(a)
safe_array=a-mx
log_sum_exp= mx + np.log(np.sum(np.exp(safe_array)))
log_sum_exp                          

89.0

Built in versions

In [24]:
np.logaddexp.reduce(a)

89.0

In [25]:
from scipy.special import logsumexp
logsumexp(a)

89.0