<a href="https://colab.research.google.com/github/serivan/DeepLearning/blob/master/02-Preliminaries/numerical_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rounding and truncation errors

Adding a very small numb er to a larger one may have no effect. This can cause large changes downstream:

In [82]:
import numpy as np

In [83]:
a = np.array([0., 1e-8]).astype('float32')
a

array([0.e+00, 1.e-08], dtype=float32)

In [84]:
(a+1)

array([1., 1.], dtype=float32)

In [85]:
a+1

array([1., 1.], dtype=float32)

exp(x) overflows for large x

In [86]:
x=88
np.exp(x).astype('float32')

1.6516363e+38

In [87]:
x=-103
np.exp(x).astype('float32')

1e-45

log(0) = - inf

In [88]:
np.log(0)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

#log(sum(exp))
Naive implementation
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf
Failure modes:
• If any entry is very large, exp overflows
• If all entries are very negative, all exps
underflow... and then log is -inf

In [89]:
a = np.array([ -100]).astype('float32')
np.log(np.sum(np.exp(a)))

-99.98309

In [90]:
a = np.array([0,88]).astype('float32')
np.log(np.sum(np.exp(a)))

88.0

Stable version

In [91]:
mx=np.max(a)
safe_array=a-mx
log_sum_exp= mx + np.log(np.sum(np.exp(safe_array)))
log_sum_exp                          

88.0

Built in versions

In [92]:
np.logaddexp.reduce(a)

88.0

In [93]:
from scipy.special import logsumexp
logsumexp(a)

88.0